### ISSUE TITLE
Line of code in documentation page needs to be updated

### ISSUE THREAD

**Issue by digitalfrost** [engineyard/ey-docs#103]
On page: http://docs.engineyard.com/asset-pipeline.html

The line:

```
run "cd #{release_path}; RAILS_ENV=#{rails_env} bundle exec rake assets:precompile"
```

should be updated to

```
run "cd #{release_path}; RAILS_ENV=#{framework_env} bundle exec rake assets:precompile"
```

**Comment by BrittTheIsh** [comment]
Thank you for the feedback digitalfrost.  We'll update our docs shortly.

**Comment by BrittTheIsh** [comment]
We've updated our Documentation with your fix.  Thanks again and feel free to fork, update and send pull requests if you're ever inclined to make any further updates.
