### ISSUE TITLE
Incorrect format for deploy hooks folder structure

### ISSUE THREAD

**Issue by drnic** [engineyard/ey-docs#114]
From http://docs.engineyard.com/use-deploy-hooks-with-engine-yard-appcloud.html under "Structure"

Instead of:

```
  APP_ROOT/
  deploy/
    before_migrate.rb
    before_symlink.rb
    before_restart.rb
    after_restart.rb
```

Remove the first line indent:

```
APP_ROOT/
  deploy/
    before_migrate.rb
    before_symlink.rb
    before_restart.rb
    after_restart.rb
```

**Comment by BrittTheIsh** [comment]
Thanks Nic. Doc updates have been deployed.  BTW it seems you've been digging through and using our docs lately.  If you see any that are missing or would be helpful to have, create a ticket under the Documentation project in YouTrack

**Comment by drnic** [comment]
You don't want me to use the big Create Issues button? Just YouTrack?

Cheers
Nic

http://engineyard.com
http://drnicwilliams.com
+1 (415) 322 9556

Engine Yard: Successful Rails Apps through Orchestration

**Comment by BrittTheIsh** [comment]
:) Do whatever's easiest for you. YouTrack goes directly into our internal queue of things we're working on.
