### ISSUE TITLE
How to specify specific bundler version?

### ISSUE THREAD

**Issue by drnic** [engineyard/ey-docs#125]
Currently we use bundler 1.0.10 during deployments. If a customer wants to use a specific version of bundler, they can add the following to their application Gemfile:

gem "bundler", "1.0.18"

Then ensure you've locked your Gemfile (updated your Gemfile.lock) before deployment.

Want to confirm it's picking up your alternate bundler version? Look in your deploy logs for "_1.0.18_"

**Comment by danishkhan** [comment]
I believe we talk about bundling your bundler here http://docs.engineyard.com/bundler-tips-for-appcloud.html

Did you want that section changed to what you have in this issue?

**Comment by drnic** [comment]
Ah ok. It didn't show up in the Google Search results - they were filled with blog and community results but no docs results.

Cheers
Nic

http://engineyard.com
http://drnicwilliams.com
+1 (415) 322 9556

Engine Yard: Successful Rails Apps through Orchestration

**Comment by danishkhan** [comment]
I think the new redesign should hopefully have a search specifically for the docs site. If not that I will add that to one of my to-dos because I agree when you do the search that happens on all EY domains it gets populate with links that might not be relevant anymore.
