### ISSUE TITLE
update method signature for bundler_10_installer

### ISSUE THREAD

**Issue by ghost** [engineyard/ey-docs#127]
The current documentation takes one parameter, but v1.4.10 of the engineyard-serverside gem takes two parameters: version, options

This is on the bottom of http://docs.engineyard.com/bundler-tips-for-appcloud.html

**Comment by drnic** [comment]
There is a bug in 1.4.10 for some customers at the moment. We're yanking it and there should be no need for doc changes once that is fixed. Sorry about the deploy issues.

## 

Dr Nic Williams
Engine Yard, VP Technology
Silicon Valley Ruby Club, President
http://engineyard.com
http://drnicwilliams.com
cell +1 (415) 860-2185

**Comment by danishkhan** [comment]
I'm going to close this issue since it should be resolved with the yanking of 1.4.10.
