### ISSUE TITLE
Fixes to keep file list

### ISSUE THREAD

**Issue by drnic** [engineyard/ey-docs#129]
Anal retentive changes to docs:

In the list "Files that can be keep files" on http://docs.engineyard.com/configuration-keep-files.html, change the following:

`/etc/monit.d/#{name}#{appname}.monitrc` --> `/etc/monit.d/#{name}.#{appname}.monitrc`

`/etc/monit.d/unicorn_#{app.name}.monitrc` --> `/etc/monit.d/unicorn_#{appname}.monitrc`

Also, group all the `/etc/` together after all the `/data/...` items. I guess, I mean, sort the list alphabetically :)

**Comment by janeday** [comment]
Fixed and deployed.
