### ISSUE TITLE
Asset pipeline optimization

### ISSUE THREAD

**Issue by ryanong** [engineyard/ey-docs#145]
You might want to suggest

``` ruby
if node[:instance_role] =~ /^app/ || node[:instance_role] == 'solo'
  run "cd #{release_path}; RAILS_ENV=#{framework_env} bundle exec rake assets:precompile"
end
```

for http://docs.engineyard.com/asset-pipeline.html

instead of just

``` ruby
run "cd #{release_path}; RAILS_ENV=#{framework_env} bundle exec rake assets:precompile"
```

This speeds up deploy quite a bit especially if you have utility instances that are slower than the application instances.

**Comment by janeday** [comment]
Hi Ryan, Thanks very much for your suggestion. I've added it to the page.
