### ISSUE TITLE
Error 102: Optimistic locking failure

### ISSUE THREAD

**Issue by zambra** [engineyard/ey-docs#15]
After a push, I get this error 
Staging Application: ............Error 102: Optimistic locking failure

when I go to my homepage, I can see this one
VCAP ROUTER: 404 - DESTINATION NOT FOUND

**Comment by danishkhan** [comment]
Are you referring to your application on AppCloud?

**Comment by zambra** [comment]
Yes

**Comment by drnic** [comment]
Zambra, this looks like a Cloud Foundry situation? ("After a push" and "VCAP ROUTER"). 

Can you please raise a ticket at http://zendesk.engineyard.com/ and explain how to reproduce this scenario? If there is a defect with the documentation for AppCloud we will come back to this then.
