### ISSUE TITLE
AppCloud JRuby 1.6.4 troubles

### ISSUE THREAD

**Issue by niclasnilsson** [engineyard/ey-docs#151]
Hi there!

I'm trying to deploy a JRuby app on AppCloud for the first time and I seem to get into all sorts of trouble. My initial trouble was to get JRuby to use --1.9 mode for my app, but as I simplified my problem, I find more basic errors that I'll start with:

I "Create New Application" and point out the EngineYard example todo app (https://github.com/engineyard/todo) to remove all errors of my own, choose Trinidad and JRuby 1.6.4 to be run on a Single Server and boot it. Provisioning seems to work, but the app can't be deployed. The full log can be viewed here (https://gist.github.com/1251754), but it ends with:

---

rake aborted!
OpenSSL::Cipher requires the jruby-openssl gem

Tasks: TOP => db:migrate => environment
## (See full trace by running task with --trace)

However, jruby-openssl is both in the Gemfile of the example app and is actually installed.

What could be wrong?

Kind regards
Niclas Nilsson

---

http://niclasnilsson.se
http://twitter.com/niclasnilsson

**Comment by niclasnilsson** [comment]
Next problem with same setup:

These are the processes listening to ports after the failed deploy:

```
$ sudo netstat -anp | grep LISTEN
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN     10990/mysqld        
tcp        0      0 0.0.0.0:6379            0.0.0.0:*               LISTEN     26689/redis-server  
tcp        0      0 0.0.0.0:11211           0.0.0.0:*               LISTEN     26663/memcached     
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN     31266/nginx.conf    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     4325/sshd           
tcp        0      0 0.0.0.0:9111            0.0.0.0:*               LISTEN     31291/monit         
tcp        0      0 0.0.0.0:8989            0.0.0.0:*               LISTEN     26693/mini_httpd    
unix  2      [ ACC ]     STREAM     LISTENING     195500   10990/mysqld        /var/run/mysqld/mysqld.sock
unix  2      [ ACC ]     STREAM     LISTENING     221147   26689/redis-server  /tmp/redis.sock
```

I decide to reboot the machine (I have still not touched a single file on the machine):

```
$ sudo reboot
```

After the machine is up again, nginx does not start automatically?

```
deploy@ip-10-127-26-72 ~ $ uptime
 13:08:55 up 5 min,  1 user,  load average: 0.00, 0.00, 0.00

deploy@ip-10-127-26-72 ~ $ sudo netstat -anp | grep LISTEN
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN     3642/mysqld         
tcp        0      0 0.0.0.0:11211           0.0.0.0:*               LISTEN     4191/memcached      
tcp        0      0 0.0.0.0:6379            0.0.0.0:*               LISTEN     4132/redis-server   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     3841/sshd           
tcp        0      0 0.0.0.0:9111            0.0.0.0:*               LISTEN     4020/monit          
tcp        0      0 0.0.0.0:8989            0.0.0.0:*               LISTEN     4135/mini_httpd     
unix  2      [ ACC ]     STREAM     LISTENING     7382     3642/mysqld         /var/run/mysqld/mysqld.sock
unix  2      [ ACC ]     STREAM     LISTENING     8659     4132/redis-server   /tmp/redis.sock
```

I suspect this is a bug in the setup?

**Comment by BrittTheIsh** [comment]
Hi @niclasnilsson.  I see that you have opened a ticket through our official support channel (https://support.cloud.engineyard.com).  I'm going to close this issue.

**Comment by drnic** [comment]
Hey Niclas, can you create a support ticket so we can discuss your specific app issues there? If we need to fix something or create new documentation, we'll come back to this ticket/create a new one. 

Thanks!
Nic

## 

Dr Nic Williams
Engine Yard, VP Technology
Silicon Valley Ruby Club, President
http://engineyard.com
http://drnicwilliams.com
cell +1 (415) 860-2185

**Comment by niclasnilsson** [comment]
Hi Nic!

https://support.cloud.engineyard.com/requests/30151

Kind regards
Niclas

**Comment by listrophy** [comment]
I'm having this same issue with jruby-openssl, but I can't find any public documentation on how to fix it. I've submitted a ticket, but getting the fix out into the public would be nice...
