### ISSUE TITLE
engineyard gem installation

### ISSUE THREAD

**Issue by lcucos** [engineyard/ey-docs#167]
I would add a small clarification:  "... install the engineyard gem on your local machine"

**Comment by BrittTheIsh** [comment]
@lcucos where do you want to see this clarification?  Which document?

**Comment by janeday** [comment]
Hi lcucos,
Aha, yes. You made a good point. I found two places in the doc set where I could include this clarification:
https://support.cloud.engineyard.com/entries/21009927-deploy-from-the-cli-engine-yard-cli-user-guide
and 
https://support.cloud.engineyard.com/entries/21009867-customize-your-environment-with-chef-recipes
Thank you.
Sincerely,
Jane
