### ISSUE TITLE
getting started - documentation suggestion

### ISSUE THREAD

**Issue by SwarmShepherd** [engineyard/ey-docs#181]
I'm finally getting a little Newbie traction and got my EY account linked to the GitHub account.  Great.  Now I'm ready to follow the instructions.  My hands are almost shaking in anticipation!  this could be it!

Your instructions follow thus:   Create an application as you **normally**  do for Engine Yard Cloud with the following exceptions:

Oh yea?   Saved somebody some trouble to write less, and maybe even most folks are experienced, but this is a complete stopper for exactly the folks that need the most help exactly when they COULD HAVE USED IT!

**Comment by janeday** [comment]
Sorry about that. I reworked the page to give a link to the standard "how to create an application" page.
