### ISSUE TITLE
http://docs.engineyard.com/find-important-log-files.html

### ISSUE THREAD

**Issue by daniel-nelson** [engineyard/ey-docs#248]
Please add /var/log/nginx/passenger.log to this list. That is the only place where "sendmail: recipients with -t option not supported" is logged (https://rails.lighthouseapp.com/projects/8994/tickets/6156-rails-3-sendmail-with-ssmtp-recipients-with-t-option-not-supported). I was tailing mail.log and syslog, but seeing nothing.

**Comment by janeday** [comment]
Done! http://docs.engineyard.com/find-important-log-files.html#topic10
Thanks very much for opening this issue.
Sincerely, Jane
