### ISSUE TITLE
Environment cluster diagram confusing

### ISSUE THREAD

**Issue by daniel-nelson** [engineyard/ey-docs#275]
The diagram at http://docs.engineyard.com/environment-cluster.html is confusing because it shows traffic (represented by arrows) to and from HAProxy on every application instance. I confirmed with support in the IRC channel that only the HAProxy on master handles traffic; HAProxy is on the slaves only for the situation in which a slave is promoted to master. It would be clearer if the arrows to and from HAProxy on the slaves were removed.

**Comment by janeday** [comment]
Thanks very much for pointing out this problem with the diagram. I posted a new version today.
Sincerely, Jane

**Comment by daniel-nelson** [comment]
Thank you
