### ISSUE TITLE
Cronjobs on Utility server

### ISSUE THREAD

**Issue by ghost** [engineyard/ey-docs#28]
Hi,

I'm having difficulty adding a custom cron job to our utility server.  I've followed everything on this page:
http://docs.engineyard.com/adding-cron-jobs.html

This page says to add a new chef recipe to add the custom cron job specifically to the utility server.

Has anyone had experience doing this?  

Below is the recipe:

if node[:name] == 'name_of_utility_server'
  cron "centricity_checker" do
    minute  '*/05'
    user    'deploy'
    command "/data/app_name/current/lib/centricity_checker.rb >> /data/app_name/shared/log/centricity_checker.log"
  end
end

**Comment by tjl2** [comment]
Hi,

Please can you open a ticket at http://support.cloud.engineyard.com ? We'll investigate what the issue is in your case and if we identify it to be incorrect instructions in that doc, we'll get it updated.

Thanks,

Tim
