### ISSUE TITLE
print page

### ISSUE THREAD

**Issue by Anjen1** [engineyard/ey-docs#291]
Hi, one thing I've noticed that kinda bugs me is when I search and find documentation at engineyard, a subsequent attempt to print the page results in a far less than printer friendly output of the content, in which the entirety of the webpage is printed, instead of the salient content. (for instance, I came here to day to grab info on migrating from ruby 1.8.6 to a newer version, and found the article, but print results in far more paper being used than if only the article itself was printed) 

Could engineyard please provide a "print" button on article pages so we can print the relevant info without having to print a bunch of extraneous content along with what we've sought?

Yes, I could copy and paste the content into Word or similar, then reformat the content and print from there, but I hope we can all agree that's a pretty darned unproductive use of time as a developer/administrator when the content itself has already been formatted...

**Comment by janeday** [comment]
Hi Andrew,
Thank you very much for your message. Yes, this is something we intend to address in the next set of revisions to our doc platform; I'm looking forward to that fix. 
My workaround is to copy and paste into a Mac Mail message; it's the best I've found for preserving format.
Sincerely,
Jane

**Comment by Anjen1** [comment]
Ah...well that makes sense...>>> for Mac Users. <<<

But for those of us who work comfortably in Windows, not so much. Thanks for the recognition of the issue anyway.

I look forward to ey's upgrade of their content server. I try to go paperless as much as possible, but it's not always an ideal method.

**Comment by janeday** [comment]
Hi Andrew,
The Engine Yard docs are now accessible from the Knowledge Base within the ticketing system. 
Pages print significantly better from this new system -- especially if I don't log in.
I hope this works for you too.
Sincerely, 
Jane

**Comment by Anjen1** [comment]
Hi Jane,

Thanks for the update on EY's doc handling. I checked a couple and the print format far cleaner.  Thank you!

Andrew Jenkins
