### ISSUE TITLE
migrating to 1.9.2 requires nginx restart

### ISSUE THREAD

**Issue by Anjen1** [engineyard/ey-docs#292]
Hi,

I followed the "Migrating to Ruby 1.9.2" document for upgrading our environment from 1.8.6 to 1.8.7, but one issue was not mentioned in the document that prevented correct operation after the change. It also requires an nginx restart to clean up the legacy components, at least when migrating from 1.8.6 to 1.8.7, although I suspect the same might be true for an upgrade to 1.9.2.
## below is Hiro Asari's reply after viewing a ticket I submitted following failure of our environment on using the doc.

We worked on this on IRC.

After updating the Ruby runtime, nginx had not been restarted. (Our document needs to be updated.) nginx is integrated to Passenger, which controls the workers. Passenger ApplicationSpawner had the old executable open, and tried to spawn a worker, but it no longer was able to find the files your application needs in order to run.
## The remedy is to restart nginx. From your vantage point, all that's needed is: ssh into the server, and do "sudo /etc/init.d/nginx restart".

Please update the doc and save some other poor soul a half day or so of unnecessary frustration?

I might even suggest that if it can be done, the restart should be automatic, but until then a documentation change seems the right thing to do...

thanks

Andrew Jenkins

**Comment by BanzaiMan** [comment]
Sorry for overlooking this issue for so long.

The issue with nginx restart applies only for those environments running Passenger. Other application servers are not affected.

**Comment by janeday** [comment]
Thanks _very_ much to Anjen1 and BanzaiMan for logging and commenting on this issue. 
I've made the adjustment to the page: http://docs.engineyard.com/migration-to-newer-ruby.html, to let Passenger users know that they need to restart Nginx. 
Sincerely,
Jane
