### ISSUE TITLE
Update Resque page

### ISSUE THREAD

**Issue by danishkhan** [engineyard/ey-docs#3]
http://docs.engineyard.com/appcloud/howtos/configure-and-deploy-resque

The resque page asks customers to contact support to request the resque script, but that script is already part of ey_monit

**Comment by emachnic** [comment]
Creating an internal ticket for this.

**Comment by betelgeuse** [comment]
Some issues with the current doc:
- The doc should be more clearly separate optional (advanced) and needed steps to get running. For example configuring resque_{x}.conf for simple needs is not needed as the defaults work just fine.
- the after_symlink.rb code line is missing sudo
- don't mix {app_name}_resque and fractalresque_resque
- the 60 seconds reference to SIGQUIT seems outdated as the installed monit.d file has a timeout of 90 seconds

In general it's my opinion that the document needs a total rework and ideally when done someone with no prior experience with setting up resque would test the new version. I found the whole experience more confusing that it should be.

**Comment by tommeier** [comment]
- It would be great to have a section on enabling resque-web to be displayed on an engineyard setup,. such as : http://blog.therubymug.com/blog/2010/04/20/engine-yard-cloud-and-resque-web.html

**Comment by emachnic** [comment]
Thanks @tommeier. I'll create an internal ticket for this and we'll work to incorporate it.

**Comment by daniel-nelson** [comment]
Referring to http://docs.engineyard.com/configure-and-deploy-resque.html, I find the instructions confusing. They refer to manually setting configurations, but also to enabling the Resque recipe. When I finally referred to the Resque recipe in https://github.com/engineyard/ey-cloud-recipes, I noticed that it takes care of all of the configuration settings (apart from deploy hooks) automatically. Simply pointing people to https://github.com/engineyard/ey-cloud-recipes and explaining what to modify (for example, does "with timeout 90 seconds" in monitrc.conf.erb achieve the same thing as "/bin/env GRACE_TIME=300"?) would have been much more straightforward.

I also found some of the documentation around the deploy hooks to be confusing. First it states "The correct way to have Resque restarted on each deploy is to have a line like:", and gives one line, but then it goes on to say there is a better way. If there is a better way, then the first way is not "correct".

**Comment by cwise** [comment]
A few other comments too...

1) The docs allude to modifying conf files but don't provide a suggestion on how to do this. Resque conf files aren't covered by the keep file mechanism. I've found the best way to do this is to modify my conf files in the chef recipes. I have several apps deployed and simply modified the resque recipe to have a different template per app (as each app can't QUEUE=\* but instead must specify their own queues/responsibility themselves)

2) Secondly, I think the resque implementation is deficient. It only handles conf files with a QUEUE= specification. In resque, a comma separated QUEUES= statement is also acceptable. The default resque script doesn't handle this (I'm working on updating that script and would like to know where I might submit that to make it a part of the EY stack).

**Comment by cwise** [comment]
There's an even simpler way to add resque-web into an existing app: https://gist.github.com/1575082

**Comment by drnic** [comment]
@cwise thanks for that link.

For the super lazy, the following "secret" link might be good too. Add this into your Rails 3 routes.rb:

``` ruby
  require "resque/server"
  mount Resque::Server.new, :at => "/resque/34257893542"
```

Change the secret number :)

**Comment by drnic** [comment]
@cwise I'm creating a new, standalone resque recipe at https://github.com/engineyard/eycloud-recipe-resque

I'd be interested in adding in the ideas you have. Want to have a chat? I'm on skype at nicwilliams or ping me via github message.

**Comment by cwise** [comment]
@drnic I'd be happy to help. Here's the updated script I've been using to support the option of a QUEUES argument:

https://gist.github.com/1579122

**Comment by cwise** [comment]
@drnic I'll try to find you on Skype as well (cwise71)

**Comment by GAV1N** [comment]
What's the status of the QUEUES fix by @cwise being incorporated into the EY stack?
