### ISSUE TITLE
Feedback on chef receipies

### ISSUE THREAD

**Issue by pehrlich** [engineyard/ey-docs#300]
http://docs.engineyard.com/custom-chef-recipes.html
- So to be clear, if I make and push my own fork, this will be read on deployment instead of the default version? 
- And when ey makes changes, I'll have to pull them in manually?
- You mention that git repos can't be inside other git repos, but this is actually supported easily with submodules
- What do the ey recepies upload/apply do under the hood? Should these be run from my app repo, or the recepies repo?  Do they become a necessary step if custom recepies are made?

Cheers

**Comment by janeday** [comment]
Hi Peter,
Thanks very much for asking these questions. I'm working on a rewrite of this page now, which I hope will clarify things. 
Sincerely,
Jane

**Comment by janeday** [comment]
Hi Peter,
The rewrite of the page about Chef recipes is now live. I tried to keep in mind your comments and questions while I did the rewrite. I hope this will help you and other readers too. Thanks again for logging this issue. 
Sincerely,
Jane
