### ISSUE TITLE
ey deploy --extra-deploy-hook-options option not documented

### ISSUE THREAD

**Issue by danp** [engineyard/ey-docs#31]
Customer on IRC was trying to figure out how to access things set via this option. Looking at the source it seems you eventually just reference your key as if it were a method in your deploy hooks.

**Comment by emachnic** [comment]
Can you please create a YouTrack ticket for this doc improvement?

Thanks,

Evan.

Sent from my iPhone

On Jun 29, 2011, at 8:14 PM, dpiddy
reply@reply.github.com
wrote:
