### ISSUE TITLE
404 Not Found  nginx/0.7.65

### ISSUE THREAD

**Issue by kumutha** [engineyard/ey-docs#32]
Hi,

I am getting  "404 Not Found nginx/0.7.65" error at the time of deploy my application. whats the solution for this problem?

**Comment by drnic** [comment]
Do you see the message, on the dashboard, "Deploy successful" or "Deploy failed"? You may be seeing the green dot but deploy may have failed.

Thanks for the idea for the docs.

If your app is deployed successfully, but you get nginx error, please raise a ticket with support. 

Cheers
Nic

http://engineyard.com
http://drnicwilliams.com
+1 (415) 322 9556

Engine Yard: Successful Rails Apps through Orchestration

**Comment by kumutha** [comment]
In Deployment history,it shows "Failed deploy of master" by username. But i am seeing the green dot for that instances. Once i visit that application it gives 404 error .... where i did a mistake ?

**Comment by drnic** [comment]
It is a known UX issue that the green dot doesn't include deploy status. Sorry about that.

Cheers
Nic

http://engineyard.com
http://drnicwilliams.com
+1 (415) 322 9556

Engine Yard: Successful Rails Apps through Orchestration

**Comment by slamet** [comment]
I having same problem with refinery cms

**Comment by slamet** [comment]
I having same problem

**Comment by BrittTheIsh** [comment]
If you are having deployment issues, please submit a support ticket at http://support.cloud.engineyard.com.

Thanks
