### ISSUE TITLE
Image Manipulation with CarrierWave

### ISSUE THREAD

**Issue by efleming** [engineyard/ey-docs#34]
We are currently using CarrierWave for image uploading and resizing, what libraries are supported for resizing?  I am currently using MiniMagick.

P.S. - We are hosting on the new JRuby platform.

**Comment by drnic** [comment]
From Thomas Enebo: image_voodoo is compatible with image_science and supports image resizing. rmagick4j will also work for this, but if it is simple stuff like resizing I recommend image_voodoo.

Let us know if you have another other issues. We'll update the docs with these ideas for JRuby

**Comment by efleming** [comment]
MiniMagick worked right out of the box, guess I should have tried it first.  But, add that to the list of things that work with JRuby.  I had tried rmagick4j before and it has trouble processing random images (no particular characteristics as far as I could tell) so you may want to keep that off the list.
