### ISSUE TITLE
ssh doesnt work for me

### ISSUE THREAD

**Issue by sasharevzin** [engineyard/ey-docs#56]
1. i read twice article that describe how to use ssh
2. issued public key without passphrase
3. added it to ssh public keys in admin
4. updated instance
5. tried to connect to remote instance
6. failed auth 

http://my.jetscreenshot.com/2777/20110725-a20d-195kb.jpg

what can i do in this case?

**Comment by joshbhamilton** [comment]
Please open a Support ticket for this issue at http://support.cloud.engineyard.com. Someone in EY's Support organization will be able to look into this for you.

**Comment by victorhazbunanuff** [comment]
I got the same problem, when i try to connect remotely. Can some one help give me a hand on this? Also i want to an update
but do not upgrade, gets stuck... this is the message:
There was an unexpected error while updating your instance. We've been notified about it - 11 hours ago
configuring instance - 113 minutes ago

**Comment by joshbhamilton** [comment]
Hi victorhazbunanuff, can you open a ticket at https://support.cloud.engineyard.com/. The Support team can help you troubleshoot your issue.
