### ISSUE TITLE
No mention of cron jobs not being recreated in cloned environments

### ISSUE THREAD

**Issue by tjl2** [engineyard/ey-docs#68]
http://docs.engineyard.com/environment-clone.html

We should mention in this doc that we don't recreate cron jobs when an environment is cloned. We should explain that this is a conservative measure to make sure that something that should only be done in a live environment isn't carried out by mistake. E.g.: you don't want a clone emailing all your customers again mentioning daily updates that have happened, or similar.

**Comment by BrittTheIsh** [comment]
Thanks Tim. Can you please create a YouTrack ticket for this issue as YouTrack is the official channel for submitting documentation requests/tickets internally.

https://engineyard.onconfluence.com/display/doc/Documentation+Process
