### ISSUE TITLE
Connecting MySQL Workbench to my hosted db

### ISSUE THREAD

**Issue by bhbeak** [engineyard/ey-docs#72]
Since MySQL Query Browser is no longer available (replaced by MySQL Workbench), I can't seem to interpret correctly the data in each field of MySQL Workbench to connect to by EY database.

The fields are:
Connection Method:  Standard TCP/IP over SSH

SSH Hostname - SSH server hostname, with optional port number
SSH Username - Name of the SSH user to connect with.
SSH Password - Password for the SSH tunnel.
SSH Key file - Path to SSH public key file.
MySQL Hostname - MySQL server host relative to the SSH server
MySQL Port - TCP/IP port of the MySQL server
Username - Name of the user to connect with.
Password - The MySQL user's password.
Default schema - The schema that will be used as default schema

Any ideas?

**Comment by shaunbrazier** [comment]
Hi, did you find out how to connect MySQL Workbench to an EngineYard database?
